fix warnings

diff --git a/ssssw b/ssssw
--- a/ssssw
+++ b/ssssw
@@ -5,16 +5,16 @@ function die() {
   local rc=$1
   shift
   local msg=$*
-  [ -z "$msg" ] || echo $msg >&2
-  exit  $rc
+  [ -z "$msg" ] || echo "$msg" >&2
+  exit  "$rc"
 }
 
 function checkenv() {
-  which openssl > /dev/null \
+  command -v openssl > /dev/null \
     || die 3 "openssl not found, please install"
-  which ssss-split > /dev/null \
+  command -v ssss-split > /dev/null \
     || die 3 "ssss-split not found, please install ssss"
-  which ssss-combine > /dev/null \
+  command -v ssss-combine > /dev/null \
     || die 3 "ssss-combine not found, please instal ssss"
 }
 
@@ -51,7 +51,7 @@ threshold=$THRESHOLD]"
   PASSPHRASE=$(openssl rand -hex 128)
 
   # Ciphering file
-  openssl enc -aes-256-cbc --base64 \
+  openssl enc -pbkdf2 --base64 \
     -in "$INPUT" \
     -out "$CIPHERED" \
     -pass stdin <<EOF || die 1
@@ -65,13 +65,14 @@ $PASSPHRASE
 EOF
 
   # Assembling passphrase share with encrypted file
-  for line in `tail -$PARTS $SSSSHARES`; do
-    N=$(echo $line | sed -E 's/.*-([0-9]+)-[0-9a-z]+/\1/')
+  for line in $(tail -$PARTS "$SSSSHARES"); do
+    N=$(echo "$line" | sed -E 's/.*-([0-9]+)-[0-9a-z]+/\1/')
     OUTPUT=$INPUT.share-$N
-    echo $line > $OUTPUT
-    echo '------ START OF FILE ------' >> $OUTPUT
-    cat $CIPHERED >> $OUTPUT
-    echo '------ END OF FILE ------' >> $OUTPUT
+    { echo "$line"; \
+      echo "------ START OF FILE ------"; \
+      cat  "$CIPHERED"; \
+      echo "------ END OF FILE ------"; \
+    } >> "$OUTPUT"
     echo "$OUTPUT"
   done
 
@@ -81,24 +82,18 @@ EOF
 
 function combine() {
   # Check all ags are actual files
-  for file in $@ ; do
+  for file in "$@" ; do
     if [[ ! -f "$file" ]]; then
       die 1 "cannot access '$file': not such file"
     fi
   done
 
   # Extract SSSS params from the 1st file
-  TOKEN=$(head -1 $1 | sed -E 's/(\[.*\]).*/\1/')
-  METAV=$(head -1 $1 | sed -E 's/\[(.*)\].*/\1/')
-  FILENAME=$(echo $METAV | tr ',' '\n' | grep 'file=' | cut -d '=' -f 2)
-  TIMESTAMP=$(echo $METAV | tr ',' '\n' | grep 'time=' | cut -d '=' -f 2)
-  PARTS=$(echo $METAV | tr ',' '\n' | grep 'parts=' | cut -d '=' -f 2)
-  THRESHOLD=$(echo $METAV | tr ',' '\n' | grep 'threshold=' | cut -d '=' -f 2)
-  #echo "FN: $FILENAME"
-  #echo "TS: $TIMESTAMP"
-  #echo "PA: $PARTS"
-  #echo "TH: $THRESHOLD"
-  #echo "TK: $TOKEN"
+  METAV=$(head -1 "$1" | sed -E 's/\[(.*)\].*/\1/')
+  FILENAME=$(echo "$METAV" | tr ',' '\n' | grep 'file=' | cut -d '=' -f 2)
+  TIMESTAMP=$(echo "$METAV" | tr ',' '\n' | grep 'time=' | cut -d '=' -f 2)
+  PARTS=$(echo "$METAV" | tr ',' '\n' | grep 'parts=' | cut -d '=' -f 2)
+  THRESHOLD=$(echo "$METAV" | tr ',' '\n' | grep 'threshold=' | cut -d '=' -f 2)
 
   # Confirm we got enough shares
   if [[ $PARTS -lt $THRESHOLD ]]; then
@@ -111,12 +106,12 @@ function combine() {
   FNM="${FILENAME%.*}"
   CIPHER="$FNM-$TIMESTAMP.$EXT.ciphered"
   PLAIN="$FNM-$TIMESTAMP.$EXT"
-  tail -n +2 $1 | grep -v '\-\-\-\-\-\-' > $CIPHER || die 1
+  tail -n +2 "$1" | grep -v '\-\-\-\-\-\-' > "$CIPHER" || die 1
 
   # Prepare ssss input appending shares
   # (remove token, as ssss's -w option don't work quite well)
   INPUT=""
-  for i in $(seq 1 $THRESHOLD); do
+  for ((i=0; i<THRESHOLD; i++)); do
     file=$1
     shift
     INPUT="$(head -1 $file | sed -E 's/\[.*\]-(.*)/\1/')\n$INPUT"
@@ -126,26 +121,26 @@ function combine() {
   # TODO: should ideally not temp write passphrase
   PASSPHRASEFN=/tmp/$(openssl rand -hex 16).passphrase
   ssss-combine -Q -t "$THRESHOLD" -x <<EOF 2> "$PASSPHRASEFN" || die 1
-$(echo -e $INPUT)
+$(echo -e "$INPUT")
 EOF
-  PASSPHRASE=$(cat $PASSPHRASEFN | grep -v WARNING)
-  rm -f $PASSPHRASEFN
-  PASSPHRASELEN=$(echo $PASSPHRASE | wc -c)
-  if [[ "$PASSPHRASELEN" != "257" ]]; then
-    die 1 "invalid recombined passphrase; len is $PASSPHRASELEN instead of 257"
+  PASSPHRASE=$(grep -v WARNING "$PASSPHRASEFN")
+  rm -f "$PASSPHRASEFN"
+  PASSPHRASELEN=${#PASSPHRASE}
+  if [[ "$PASSPHRASELEN" != "256" ]]; then
+    die 1 "invalid recombined passphrase; len is $PASSPHRASELEN instead of 256"
   fi
 
   # Decrypt file
-  openssl enc -d --aes-256-cbc --base64 \
+  openssl enc -d -pbkdf2 --base64 \
     -in "$CIPHER" \
     -out "$PLAIN" \
     -pass stdin <<EOF || die 1
 $PASSPHRASE
 EOF
-  rm $CIPHER
+  rm "$CIPHER"
 
   # We're done, simply output the filename
-  echo $PLAIN
+  echo "$PLAIN"
 
 }
 
@@ -167,7 +162,7 @@ function help() {
   echo
   echo "COMMAND: $PROGNAME combine FILE [FILE ...]"
   echo "  Re-combine shares back into the original file. The files shall be the"
-  echo "  ones generated by $PORGNAME split and there must be enough of them for"
+  echo "  ones generated by $PROGNAME split and there must be enough of them for"
   echo "  reaching the ssss threshold."
   echo
   echo "ARGUMENTS"
@@ -188,11 +183,11 @@ case $action in
     ;;
   'split')
     checkenv
-    split $@
+    split "$@"
     ;;
   'combine')
     checkenv
-    combine $@
+    combine "$@"
     ;;
   *)
     echo "Invalid command, must be {split|combine}; type '$0 --help' for help."
